spring:
  application:
    name: kafka-sasl

  # Kafka properties
  kafka:
    security:
      protocol: "SASL_PLAINTEXT"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
      properties:
        sasl:
          jaas:
            config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin-secret\";"
          mechanism: "PLAIN"
